spring:
  application:
    name: beyondsight
    version: 1.0.0

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: notverysecret

  ai:
    mcp:
      server:
        name: beyondsight-mcp-server
        version: 1.0.0
        type: SYNC
        instructions: "These tools allows to find code usages on the project. Don't use grep to find code usages."
        sse-message-endpoint: /mcp/message
        enabled: true
        capabilities:
          tool: true

logging:
  level:
    root: DEBUG
    com: DEBUG

    org:
      neo4j:
        driver: DEBUG